project:
  type: website

website:
  title: "CODAMUS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - team.qmd
      - projects.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



